### ISSUE TITLE
Links to legislation explorer are wrong

### ISSUE THREAD

**Issue by edarin** [openfisca/openfisca-web-ui#15]
Example: edit a person, click on the "?" near `Année de naissance`

**Comment by benjello** [comment]
A commit recently renamed birth to date_naissance in openfisca-france/master

**Comment by edarin** [comment]
For all variables, it's not working : links are dead. One should change www.openfisca.fr/tools/variables/name_of_variable to legislation.openfisca.fr/variables/name_of_variables.

But still looking where the url is stocked..
