### ISSUE TITLE
Réforme inversion_revenus inutile

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-web-ui#9]
À partir du moment où l'UI (branche `next`) demande non plus le salaire imposable, mais le [salaire de base](http://legislation.openfisca.fr/variables/salaire_de_base) il n'est pas utile d'appeler la réforme d'inversion de revenus.

**Comment by cbenz** [comment]
933e88a2b7542426c69a0b317f582e8f14a5c66f
a74151f8cfd16f68c8ca8ef1b0a0393d61b5f4ac

Deployé sur http://ui-test.openfisca.fr/

**Comment by iDevelopper** [comment]
Je pense que l'UI devrait permettre de demander le salaire de base pour l'individu mais aussi le salaire imposable pour le foyer, comme le fait le simulateur sur gouv.impots.fr

**Comment by cbenz** [comment]
@iDevelopper Peux-tu faire une nouvelle issue pour cela ? Je préfère en faire plusieurs mais bien ciblées.
